### ISSUE TITLE
Fehler bei Eingabe eines Leerzeichens in der Suchleiste  bei "target": ".ct-search-ui"

### ISSUE THREAD

**Issue by SteffenTschan-Surrey** [conterra/mapapps-intro#10]
Die Eingabe eines Leerzeichens in der Suchleiste führt bei "target": ".ct-search-ui" dazu, dass der nächste Stepp initialisiert wird.
Dies obwohl in der Konfiguration "nextOnTargetClick": false eingetragen ist.

Versionen: 
Map.Apps 4.14.2
dn_intro 2.0.3

**Comment by sholtkamp** [comment]
Fixed in #11
