### ISSUE TITLE
Display Issue when windowTitle too long

### ISSUE THREAD

**Issue by Hisendur** [conterra/mapapps-intro#3]
When the windowTitle of the welcome window is changed to a much longer Text and the box can word-wrap, the entire box gets unreadable.

![grafik](https://user-images.githubusercontent.com/25455737/73245417-761cca00-41ac-11ea-8443-6f51e1d6baf9.png)

css-changes:

.everlasting .dijitDialogTitle {
    text-align: center;
    white-space: normal !important;
}

Can the width of the window be changed?

**Comment by matthiasstein** [comment]
The window can be adjusted. Click here for more information: https://developernetwork.conterra.de/en/documentation/mapapps/cookbook/customizing-windows-and-repositioned-widgtes-without-touching
