### ISSUE TITLE
all addressed windows opening in Firefox

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-intro#7]
When using the Firefox browser starting the intro results (most times) in opening all windows/tools that are addressed by the intro-tool.

**Comment by matthiasstein** [comment]
The Intro Bundle must open all tools used in the Intro at startup so that the CSS classes are present and can be used by the Intro.

What exactly is the problem? Do the windows close again or do they stay open?

**Comment by kbor-maschmi** [comment]
The windows open at startup and stay open. Some buttons are flickering like they are pressed over and over again.

**Comment by matthiasstein** [comment]
Does this happen in the sample app as well?
https://demos.conterra.de/mapapps/resources/apps/downloads_intro_4x/index.html?lang=de

If not can you provide your intro configuration?

**Comment by matthiasstein** [comment]
Could you check if this new version fixes the error?
https://github.com/conterra/mapapps-intro/releases/tag/2.0.2

**Comment by kbor-maschmi** [comment]
The sample app with its default-configuration does not seem to produce the error. When adding several "dummy"-custominfo-buttons (opening a window each) which are also addressed by the intro the error occurs from time to time.

I added our app so you can see how our intro configuration looks like
[gda_intro_test.zip](https://github.com/conterra/mapapps-intro/files/6507474/gda_intro_test.zip)

Sadly the new version does not fix the error.

**Comment by matthiasstein** [comment]
TODO: Einschränkungen dokumentieren

**Comment by MartinOver2** [comment]
Raising the timeout value works for me in all Browsers (UserIntro.js): 

async(() => {tool.set("active", false); }, **1000**);
... and .... 

async(() => {
              if (appCtx._applicationRootNode.removeClassName !== undefined) {               appCtx._applicationRootNode.removeClassName("dn_intro_initializing");
                } else {
                    appCtx._applicationRootNode.className = appCtx._applicationRootNode.className.replace("dn_intro_initializing", "");
                }
            }, **1100**);

**Comment by sholtkamp** [comment]
Idea: Make timeout configurable on a case by case basis
